version: '3.0'
services:
  rasa:
    build:
      context: ./Kisan Mitra
      dockerfile: ./Dockerfile
    image: rasa/rasa:2.8.5-full
    ports:
      - 5005:5005
      
  action-server:
    build:
      context: ./Kisan Mitra/actions
      dockerfile: ./Dockerfile
    image: rasa/rasa-sdk:2.8.2
    ports: 
      - 5055:5055

  frontend:
    build:
      context: ./kisan-mitra-frontend
      dockerfile: ./Dockerfile
    image: kisan-mitra-frontend
    ports:
      - "3000:3000"
    depends_on:
    - backend

  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: kisan-mitra-backend
    ports:
      - "3001:3001"
